title: HYPRSENSE
description: Lückenschluss im Open Source Entwurfsfluss für ganzheitliches Chipdesign für smarte Sensor-Systeme mittels virtueller Prototypen
logo: /logo.png
theme: jekyll-theme-minimal