title: DI-HYPRSENSE
description: "<br><br>Lückenschluss im Open Source Entwurfsfluss für ganzheitliches Chipdesign für smarte Sensor-Systeme mittels virtueller Prototypen.<br><br><img src='./BmftrLogo.png' alt='Gefoerdert durch das BMFTR' style='max-width: 100%; height: auto; margin-top: 5px;'>"
logo: /logo.png
theme: jekyll-theme-minimal